language: php

php:
    - 7.0

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE blog_api_test;' -U postgres
  - psql -c 'CREATE DATABASE  blog_api_dev;' -U postgres
  - psql -c 'CREATE DATABASE  blog_api;' -U postgres
  - composer self-update
  - composer install
  - composer dump-autoload -o
  - php bin/console doctrine:schema:create --env=test

script:
  phpunit --configuration="phpunit.xml"

notifications:
  email:
    -  info@marcel-edmund-franke.de