<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * Class ArticleRepository
 * @package AppBundle\Repository
 */
class ArticleRepository extends EntityRepository
{
    /**
     * @param $name
     * @return array
     */
    public function findAllByTag($name){

       $query = $this->createQueryBuilder('a')
                     ->select('a.*, t.*, u.*')
                     ->leftJoin('Tag', 't')
                     ->leftJoin('User', 'u')
                     ->where('t.name = ?', $name)
                     ->getQuery();

        try{
            $result = $query->getResult();
        }catch (NoResultException $e){
            return array();
        }

        return $result;
    }
}
