<?php

namespace AppBundle\Repository;

/**
 * ArticleContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleContentRepository extends \Doctrine\ORM\EntityRepository
{
}
