<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * Class ArticleRepository
 * @package AppBundle\Repository
 */
class ArticleRepository extends EntityRepository
{
    /**
     * @param $name
     * @param $maxResults
     * @return array
     */
    public function findAllArticlesByTag($name, $maxResults){

       $query = $this->createQueryBuilder('a')
                     ->join('AppBundle\Entity\Tag', 't', 'WITH', 't.name LIKE :name')
                     ->setMaxResults($maxResults)
                     ->setParameter('name', $name)
                     ->getQuery();

        try{
            $result = $query->getArrayResult();
        }catch (NoResultException $e){
            return array();
        }

        return $result;
    }
}
