<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * Class TagRepository
 * @package AppBundle\Repository
 */
class TagRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findAllNames() {
        
        $query = $this->createQueryBuilder('t')
            ->select('DISTINCT t.name')
            ->getQuery();

        try{
            $result = $query->getArrayResult();
        }catch(NoResultException $e){
            return array();
        };

        return $result;
    }
}
