Hateoas\Representation\RouteAwareRepresentation:
    exclusion_policy: ALL
    properties:
        inline:
            groups: ["viewdata_list"]
            inline: true
            expose: true
    relations:
        -
            rel: self
            href:
                route: expr(object.getRoute())
                parameters: expr(object.getParameters())
            absolute: expr(object.isAbsolute())
            exclusion:
                groups: ["viewdata_list", "viewdata_reverse_list"]