services:
    appbundle.article.workflow:
        class: AppBundle\Library\Workflow\ArticleWorkflow
        public: true
        calls:
          - [setContainer, ["@service_container"]]
          - [setRepositoryName, ["AppBundle:Article"]]

    appbundle.articlecontent.workflow:
        class: AppBundle\Library\Workflow\ArticleContentWorkflow
        public: true
        calls:
          - [setContainer, ["@service_container"]]
          - [setRepositoryName, ["AppBundle:ArticleContent"]]

    appbundle.user.workflow:
            class: AppBundle\Library\Workflow\UserWorkflow
            public: true
            calls:
              - [setContainer, ["@service_container"]]
              - [setRepositoryName, ["AppBundle:User"]]

    appbundle.tag.workflow:
            class: AppBundle\Library\Workflow\TagWorkflow
            public: true
            calls:
              - [setContainer, ["@service_container"]]
              - [setRepositoryName, ["AppBundle:Tag"]]